import type { Employee } from "~/types";

export const employees: Employee[] = [
    {
        id: 1,
        avatar: 'default',
        name: 'Мартынова Татьяна',
        job_title: 'Менеджер проектов',
        email: 'mart@mail.ru',
        in_the_team: '9 лет 3 месяца',
    },{
        id: 2,
        avatar: 'default',
        name: 'Зайцева Мария',
        job_title: 'Менеджер проектов',
        email: 'zayceva@mail.ru',
        in_the_team: '5 лет 3 месяца',
    },{
        id: 3,
        avatar: 'default',
        name: 'Шевченко Наталья',
        job_title: 'Менеджер проектов',
        email: 'shevchenko@mail.ru',
        in_the_team: '5 лет 3 месяца',
    },{
        id: 4,
        avatar: 'default',
        name: 'Абашина Ксения',
        job_title: 'Менеджер проектов',
        email: 'abashina@mail.ru',
        in_the_team: '5 лет 3 месяца',
    },{
        id: 5,
        avatar: 'default',
        name: 'Иванов Павел',
        job_title: 'Фронтенд-разработчик',
        email: 'ivanov@mail.ru',
        in_the_team: '4 года 1 месяц',
    },{
        id: 6,
        avatar: 'default',
        name: 'Пономарев Дмитрий',
        job_title: 'Фронтенд-разработчик',
        email: 'ponomarev@mail.ru',
        in_the_team: '5 лет 3 месяца',
    },{
        id: 7,
        avatar: 'default',
        name: 'Дедищев Павел',
        job_title: 'Бэкенд-разработчик',
        email: 'dedishev@mail.ru',
        in_the_team: '1 год 11 месяцев',
    },{
        id: 8,
        avatar: 'default',
        name: 'Громова Ирина',
        job_title: 'Бэкенд-разработчик',
        email: 'gromova@mail.ru',
        in_the_team: '1 год 11 месяцев',
    },{
        id: 9,
        avatar: 'default',
        name: 'Дозоров Александр',
        job_title: 'Бэкенд-разработчик',
        email: 'dozorov@mail.ru',
        in_the_team: '5 лет 3 месяца',
    },{
        id: 10,
        avatar: 'default',
        name: 'Трутнев Иван',
        job_title: 'Бэкенд-разработчик',
        email: 'trutnev@mail.ru',
        in_the_team: '5 лет 3 месяца',
    },{
        id: 11,
        avatar: 'default',
        name: 'Чебатков Евгений',
        job_title: 'Тестировщик',
        email: 'chebatkov@mail.ru',
        in_the_team: '6 лет 3 месяца',
    },{
        id: 12,
        avatar: 'default',
        name: 'Алексей Щербаков',
        job_title: 'Бэкенд-разработчик',
        email: 'cherbakov@mail.ru',
        in_the_team: '5 лет 3 месяца',
    },{
        id: 13,
        avatar: 'default',
        name: 'Макаров Илья',
        job_title: 'Бэкенд-разработчик',
        email: 'makarov@mail.ru',
        in_the_team: '5 лет 3 месяца',
    },{
        id: 14,
        avatar: 'default',
        name: 'Нурлан Сабуров',
        job_title: 'Бэкенд-разработчик',
        email: 'saburov@mail.ru',
        in_the_team: '5 лет 3 месяца',
    },{
        id: 15,
        avatar: 'default',
        name: 'Тамби Масаев',
        job_title: 'Бэкенд-разработчик',
        email: 'masaev@mail.ru',
        in_the_team: '5 лет 3 месяца',
    },{
        id: 16,
        avatar: 'default',
        name: 'Эмир Кашоков',
        job_title: 'Бэкенд-разработчик',
        email: 'kashokov@mail.ru',
        in_the_team: '5 лет 3 месяца',
    },{
        id: 17,
        avatar: 'default',
        name: 'Артур Чапарян',
        job_title: 'Бэкенд-разработчик',
        email: 'chaparyan@mail.ru',
        in_the_team: '5 лет 3 месяца',
    },{
        id: 18,
        avatar: 'default',
        name: 'Иван Абрамов',
        job_title: 'Бэкенд-разработчик',
        email: 'abramov@mail.ru',
        in_the_team: '5 лет 3 месяца',
    },{
        id: 19,
        avatar: 'default',
        name: 'Иван Усович',
        job_title: 'Бэкенд-разработчик',
        email: 'usovich@mail.ru',
        in_the_team: '5 лет 3 месяца',
    },{
        id: 20,
        avatar: 'default',
        name: 'Расул Чабдаров',
        job_title: 'Бэкенд-разработчик',
        email: 'chabdarov@mail.ru',
        in_the_team: '5 лет 3 месяца',
    }
];
